[package]
name = "exploit_cve_2021_21315"
version = "0.1.0"
authors = ["Ki11ion4ir3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
urlencoding = "2.1.0"
curl = "0.4.41"
